### ISSUE TITLE
Bug when importing pyzed.sl

### ISSUE THREAD

**Issue by Rudiio** [stereolabs/zed-python-api#227]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues.
- [X] This issue is not a question, feature request, or anything other than a bug report directly related to this project.

### Description

After installing the ZED python API, I keep getting an error when trying to import pyzed.sl.
This is the error message that I get : 
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "pyzed/sl.pyx", line 7940, in init pyzed.sl
  File "pyzed/sl.pyx", line 5976, in pyzed.sl.InitParameters.__cinit__
TypeError: Argument is not of right type.

### Steps to Reproduce

Importing pyzed.sl in python

### Expected Result

Importing pyzed.sl and using the ZED python API

### Actual Result

I get the error :
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "pyzed/sl.pyx", line 7940, in init pyzed.sl
  File "pyzed/sl.pyx", line 5976, in pyzed.sl.InitParameters.__cinit__
TypeError: Argument is not of right type.

### ZED Camera model

ZED2

### Environment

```shell
OS : Ubuntu 22
Graphics: Nvidia RTX 3060
CUDA: 11.8
Python: 3.10
Zed SDK: 4.0.5
```

**Comment by imdsafi09** [comment]
Hi, did you find any solution for this problem? I am facing the same issue.
