### ISSUE TITLE
(Solved) ImportError: DLL load failed: The specified module could not be found

### ISSUE THREAD

**Issue by linthy** [stereolabs/zed-python-api#69]
I follow the READMY.md to install the Prerequisites. 
I could run setup.py without any problem and even import pyzed. 
When I try to run tutorials, the program  error.

In IDE:
>File "d:\PY_source\ZED\zed-python-api-master\tutorials\hello_zed.py", line 25, in <module>
    import pyzed.sl as sl
ImportError: DLL load failed: The specified module could not be found.

In cmd
 >\>>>import pyzed.sl
Traceback (most recent call last):
  File "\<stdin\>", line 1, in \<module\>
ImportError: No module named 'pyzed.sl'

I am running this on Windows10 with Anaconda, python 3.5.5 ,Let me know if you need more information.
Someone said that the error possibly  occurred by using Anaconda, but I don't know how to solve.
Does anyone know how to fix this? 
Thank you  very much.

My computer is with CUDA 9.1，CUDnn 7.05.
when I install ZED SDK, it said CUDA 10 is mandatory dependence. So I don't know I should reinstall CUDA.

**Comment by linthy** [comment]
> I follow the READMY.md to install the Prerequisites.
> I could run setup.py without any problem and even import pyzed.
> When I try to run tutorials, the program error.
> 
> File "d:\PY_source\ZED\zed-python-api-master\tutorials\hello_zed.py", line 25, in 
> import pyzed.sl as sl
> ImportError: DLL load failed: The specified module could not be found.
> 
> I am running this on Windows10 with Anaconda, python 3.5.5 ,Let me know if you need more information.
> Someone said that the error possibly occurred by using Anaconda, but I don't know how to solve.
> Does anyone know how to fix this?
> Thank you very much.

CUDA 9.1，CUDnn 7.05

**Comment by linthy** [comment]
Hi，I solve this question. Because of different version CUDA-Toolkit, the program can't work.

So I have reinstalled my CUDA from 9.1 to 9.0,  then it can import pyzed.sl.

I guess zed-sdk only support to CUDA9.0  and CUDA10.0.
