### ISSUE TITLE
zipfile.BadZipFile: File is not a zip file

### ISSUE THREAD

**Issue by Qiulin-W** [stereolabs/zed-python-api#91]
when I try to install pyzed from the http url, I got the following error:

(base) qiulin@qiulin-G3-3579:~$ pip3 install https://download.stereolabs.com/whl/cu90/pyzed-2.8-cp36-cp36m-linux_x86_64.whl
Collecting pyzed==2.8 from https://download.stereolabs.com/whl/cu90/pyzed-2.8-cp36-cp36m-linux_x86_64.whl
  Downloading https://download.stereolabs.com/whl/cu90/pyzed-2.8-cp36-cp36m-linux_x86_64.whl
     - 51kB 41kB/s
ERROR: Exception:
Traceback (most recent call last):
  File "/home/qiulin/anaconda3/lib/python3.6/site-packages/pip/_internal/cli/base_command.py", line 188, in main
    status = self.run(options, args)
  File "/home/qiulin/anaconda3/lib/python3.6/site-packages/pip/_internal/commands/install.py", line 345, in run
    resolver.resolve(requirement_set)
  File "/home/qiulin/anaconda3/lib/python3.6/site-packages/pip/_internal/legacy_resolve.py", line 196, in resolve
    self._resolve_one(requirement_set, req)
  File "/home/qiulin/anaconda3/lib/python3.6/site-packages/pip/_internal/legacy_resolve.py", line 359, in _resolve_one
    abstract_dist = self._get_abstract_dist_for(req_to_install)
  File "/home/qiulin/anaconda3/lib/python3.6/site-packages/pip/_internal/legacy_resolve.py", line 307, in _get_abstract_dist_for
    self.require_hashes
  File "/home/qiulin/anaconda3/lib/python3.6/site-packages/pip/_internal/operations/prepare.py", line 199, in prepare_linked_requirement
    progress_bar=self.progress_bar
  File "/home/qiulin/anaconda3/lib/python3.6/site-packages/pip/_internal/download.py", line 1050, in unpack_url
    progress_bar=progress_bar
  File "/home/qiulin/anaconda3/lib/python3.6/site-packages/pip/_internal/download.py", line 914, in unpack_http_url
    unpack_file(from_path, location, content_type, link)
  File "/home/qiulin/anaconda3/lib/python3.6/site-packages/pip/_internal/utils/misc.py", line 738, in unpack_file
    flatten=not filename.endswith('.whl')
  File "/home/qiulin/anaconda3/lib/python3.6/site-packages/pip/_internal/utils/misc.py", line 615, in unzip_file
    zip = zipfile.ZipFile(zipfp, allowZip64=True)
  File "/home/qiulin/anaconda3/lib/python3.6/zipfile.py", line 1108, in __init__
    self._RealGetContents()
  File "/home/qiulin/anaconda3/lib/python3.6/zipfile.py", line 1175, in _RealGetContents
    raise BadZipFile("File is not a zip file")
zipfile.BadZipFile: File is not a zip file

I tried to install in the following way: 
pip3 install --no-cache-dir https://download.stereolabs.com/whl/cu90/pyzed-2.8-cp36-cp36m-linux_x86_64.whl
but it doesn't work for me. Could anyone give me some help on this? Thanks!

**Comment by adujardin** [comment]
The package for Python 3.6, CUDA 9.0 doesn't exist yet, the page is therefore redirected into the https://www.stereolabs.com webpage. Which means pip downloaded an HTML page and complains that it can't install it.

The support for the packaged version is currently quite limited and will be extended in the future. 

For now, you can check if the package is available by simply trying to download it manually, by clicking the link and see if the redirection appears.

In your case, you will have to follow the instruction in the [README](https://github.com/stereolabs/zed-python-api#installing-the-plugin-using-pip) to install the pyzed package.
